/// Flutter icons SoCalLogos
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SoCalLogos
///      fonts:
///       - asset: fonts/SoCalLogos.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SoCalLogos {
  SoCalLogos._();

  static const _kFontFam = 'SoCalLogos';
  static const String? _kFontPkg = null;

  static const IconData youtube = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medium = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
