name: Generate Burn Address and NFT Minting Tx
on: 
  workflow_dispatch:
    inputs:
      network:
        description: 'Cardano Network'
        required: true
        default: 'mainnet'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup Haskell
      uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.10.7'
        cabal-version: 'latest'
    
    - name: Install Packages
      run: sudo apt-get install libssl-dev libtinfo-dev libsystemd-dev zlib1g-dev libsodium-dev jq -y
        
    - name: Make Inputs for Plutus Script
      working-directory: ./res/scripts
      run: |
        chmod +x `ls *.sh`
        ./network-tag.sh ${{ github.event.inputs.network }}
        ./token-name.sh
      shell: bash
        
    - name: Compile Plutus Script
      working-directory: ./res
      run: |
        cabal v2-update
        cabal v2-run burn-ada.cabal -- ${{ github.event.inputs.network }}
      
    - name: Build Transaction Script
      working-directory: ./res/scripts
      run: |
         chmod +x `ls *.sh`
         ./build-tx-script.sh
      shell: bash
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Archived Outputs
        path: ./res/cache
        
    - name: Push to New Branch
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: '${{ github.event.inputs.network }}-build'
        FOLDER: res/cache
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
