name: Generate Random Address
on: 
  workflow_dispatch:

# TODO: Create a job that will create a fork of the GitHub repository.
jobs:
  run_scripts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      run: git checkout HEAD^
    - name: Run Script Files
      uses: ./res/bin
      run: |
         chmod +x ./res/scripts/rando-addr.sh
         chmod +x ./res/scripts/token-name.sh
         chmod +x ./res/scripts/gen-policyID.sh
         chmod +x ./res/scripts/gen-metadata.sh
         chmod +x ./res/scripts/build-tx-script.sh
         ./res/scripts/rando-addr.sh
         ./res/scripts/token-name.sh
         ./res/scripts/gen-policyID.sh
         ./res/scripts/gen-metadata.sh
         ./res/scripts/build-tx-script.sh
      shell: bash
    - name: Upload Artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
          path: ./res/cache
  # pull_request:
  #   needs: run_scripts
  #   runs-on: ubuntu-latest
