name: Generate Random Address
on: 
  workflow_dispatch

# TODO: Create a job that will create a fork of the GitHub repository.
jobs:

  #compile_plutus_script:
   # runs-on: ubuntu-latest
    #steps:
    #- name: Environment Setup
    #- uses: actions/checkout@v2
    #- uses: actions/setup-haskell@v1
      #with:
        #ghc-version: '8.10.4'
        #cabal-version: '2.4'

    #- name: Cabal Run
      #working-directory: ./res
      #run: cabal run burn-ada.cabal

  run_scripts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Setup Haskell
      uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.10.1'
        cabal-version: '2.4'
    - name: Run Script Files
      working-directory: ./res/scripts
      run: |
         chmod +x `ls *.sh`
         ./rando-addr.sh
         ./gen-policyID.sh
         ./gen-metadata.sh
         ./build-tx-script.sh
      shell: bash
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Archive Outputs
        path: ./res/cache
  #  - name: Rename Local Branch
  #    run: git branch -m <auto-branch>
  # pull_request:
  #   needs: run_scripts
  #   runs-on: ubuntu-latest
