name: Generate Random Address
on: 
  workflow_dispatch

# TODO: Create a job that will create a fork of the GitHub repository.
jobs:
  run_scripts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Run Script Files
      working-directory: ./res/scripts
      run: |
         chmod +x rando-addr.sh
         chmod +x token-name.sh
         chmod +x gen-policyID.sh
         chmod +x gen-metadata.sh
         chmod +x build-tx-script.sh
         ./rando-addr.sh
         ./token-name.sh
         ./gen-policyID.sh
         ./gen-metadata.sh
         ./build-tx-script.sh
      shell: bash
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Archive Outputs
        path: ./res/cache
    - name: Rename Local Branch
      run: git branch -m <auto-branch>
  # pull_request:
  #   needs: run_scripts
  #   runs-on: ubuntu-latest
